import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { TraceSession, scoreStroke } from '../public/stroke-scorer.mjs';

// Generated by running the actual Dart StrokeScorer on all 12 app strokes:
// exact, reversed, small offset, large offset, and incomplete paths.
const fixtures = JSON.parse(readFileSync(new URL('./app-scorer-fixtures.json', import.meta.url)));
test('all 60 scores match the running Flutter app', () => {
  assert.equal(fixtures.length, 60);
  for (const fixture of fixtures) {
    const actual = scoreStroke(fixture.user, fixture.expected, fixture.canvasSize);
    for (const key of ['passed', 'directionOk', 'startPointOk']) assert.equal(actual[key], fixture.score[key], `${fixture.id}: ${key}`);
    for (const key of ['frechet', 'accuracy']) assert.ok(Math.abs(actual[key] - fixture.score[key]) < 1e-8, `${fixture.id}: ${key}`);
  }
});
const expected = [[40, 150], [150, 150], [260, 150]];
test('three failed attempts advance with assistance, never independent success', () => {
  const session = new TraceSession([expected, expected], 300);
  const reversed = expected.toReversed();
  assert.equal(session.submit(reversed).advanced, false);
  assert.equal(session.submit(reversed).advanced, false);
  assert.equal(session.submit(reversed).assisted, true);
  assert.equal(session.index, 1);
  assert.equal(session.attempts, 0);
  session.submit(expected);
  assert.equal(session.done, true);
  assert.equal(session.passed, 1);
  assert.equal(session.allPassed, false);
  assert.equal(session.accuracy, 0.5);
  assert.equal(session.submit(expected), null);
});
test('taps do not consume attempts; a fresh session clears all progress', () => {
  const session = new TraceSession([expected], 300);
  assert.equal(session.submit([[40, 150]]), null);
  assert.equal(session.attempts, 0);
  session.submit(expected);
  assert.equal(session.allPassed, true);
  const fresh = new TraceSession([expected], 300);
  assert.equal(fresh.index, 0);
  assert.equal(fresh.accuracy, 0);
  assert.equal(fresh.allPassed, false);
});
test('empty data does not count as mastery', () => {
  const session = new TraceSession([]);
  assert.equal(session.allPassed, false);
  assert.equal(session.submit(expected), null);
});
test('asset transforms reproduce the app coordinates exactly', () => {
  for (const char of ['明', '木']) {
    const glyph = JSON.parse(readFileSync(new URL(`../public/assets/hanzi/${char}.json`, import.meta.url)));
    assert.equal(glyph.strokes.length, glyph.medians.length);
    assert.equal(glyph.descriptions.length, glyph.medians.length);
    glyph.medians.forEach((median, index) => {
      const s = 600 / 1024 * glyph.fit.scale;
      const transformed = median.map(([x, y]) => [300 + (x - glyph.fit.center[0]) * s, 300 - (y - glyph.fit.center[1]) * s]);
      const fixture = fixtures.find((f) => f.id === `${char}-${index}-0`);
      transformed.forEach((point, i) => point.forEach((value, axis) => assert.ok(Math.abs(value - fixture.expected[i][axis]) < 1e-8)));
    });
  }
});
